# compose.yaml
version: '3.8'

services:
  # ==========================================================
  # NODO MATRIZ (ASUNCIÓN)
  # ==========================================================
  postgres-matriz:
    image: postgres:15-alpine
    container_name: cpd-matriz-db
    networks:
      - red_empresarial
    #ports:
    #  - "5432:5432" # Puerto PostgreSQL estándar para el host físico
    environment:
      POSTGRES_DB: matriz_db
      POSTGRES_USER: ucom_admin
      #POSTGRES_PASSWORD: password_matriz
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - datos_matriz:/var/lib/postgresql/data
    secrets:
      - db_password
    # Gobernanza Cgroups v2: límites físicos de silicio
    deploy:
      resources:
        limits:
          cpus: '0.50'        # Máximo 50% de un núcleo de CPU
          memory: 512M        # Evita consumos mayores a 512 Megabytes de RAM
        reservations:
          memory: 256M        # Reserva mínima de 256 MB de RAM garantizada
  # ==========================================================
  # NODO SUCURSAL A (CIUDAD DEL ESTE)
  # ==========================================================
  postgres-sucursal-a:
    image: postgres:15-alpine
    container_name: cpd-sucursala-db
    networks:
      - red_empresarial
    ports:
      - "5433:5432" # Redireccionamos el puerto 5433 del host al 5432 interno
    environment:
      POSTGRES_DB: sucursal_a_db
      POSTGRES_USER: ucom_admin
      POSTGRES_PASSWORD: password_sucursal_a
    volumes:
      - datos_sucursal_a:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.25'        # Límite estricto de 255% de CPU
          memory: 256M        # Máximo de 256 MB de RAM
        reservations:
          memory: 128M        # Garantía mínima de 128 MB
  # ==========================================================
  # NODO SUCURSAL B (ENCARNACIÓN)
  # ==========================================================
  postgres-sucursal-b:
    image: postgres:15-alpine
    container_name: cpd-sucursalb-db
    networks:
      - red_empresarial
    ports:
      - "5434:5432" # Redireccionamos el puerto 5434 del host al 5432 interno
    environment:
      POSTGRES_DB: sucursal_b_db
      POSTGRES_USER: ucom_admin
      POSTGRES_PASSWORD: password_sucursal_b
    volumes:
      - datos_sucursal_b:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          memory: 128M
  # ==========================================================
  # NODO SUCURSAL C (CORONEL OVIEDO)
  # ==========================================================
  postgres-sucursal-c:
    image: postgres:15-alpine
    container_name: cpd-sucursalc-db
    networks:
      - red_empresarial
    ports:
      - "5435:5432" # Redireccionamos el puerto 5435 del host al 5432 interno
    environment:
      POSTGRES_DB: sucursal_c_db
      POSTGRES_USER: ucom_admin
      POSTGRES_PASSWORD: password_sucursal_c
    volumes:
      - datos_sucursal_c:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          memory: 128M
# ==========================================================
  # BALANCEADOR DE CARGA TCP (HA-PROXY CAPA 4 EN EL BORDE)
  # ==========================================================
  cpd-balanceador:
    image: haproxy:2.8-alpine
    container_name: cpd-balanceador
    ports:
      - "5432:5432"          # Único puerto expuesto en el host para canalizar el tráfico a la Matriz
    networks:
      - red_empresarial
    volumes:
      - ./balanceador/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - postgres-matriz
  # ==========================================================
  # TELEMETRÍA: PROMETHEUS (TSDB)
  # ==========================================================
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: cpd-prometheus
    ports:
      - "9090:9090" # Exponemos la consola web de Prometheus
    networks:
      - red_empresarial
    volumes:
      - ./monitoreo/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - datos_prometheus:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway" # Permite a Prometheus conectarse al Host de Codespaces
    depends_on:
      - postgres-matriz

  # ==========================================================
  # VISUALIZACIÓN: GRAFANA
  # ==========================================================
  grafana:
    image: grafana/grafana-oss:10.0.3
    container_name: cpd-grafana
    ports:
      - "3000:3000" # Exponemos la interfaz web de Grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Credenciales de inicio de laboratorio
    networks:
      - red_empresarial
    volumes:
      - datos_grafana:/var/lib/grafana
    depends_on:
      - prometheus
# Definición de la Red y Sistemas de Almacenamiento Lógicos
networks:
  red_empresarial:
    driver: bridge # Creamos un conmutador de red (switch virtual) personalizado

volumes:
  datos_matriz:
  datos_sucursal_a:
  datos_sucursal_b:
  datos_sucursal_c:
  datos_prometheus:
  datos_grafana:
# Declaración del Secret local
secrets:
  db_password:
    file: ./db_password.txt